platform:
  - x64

install:
  - cmd: SET PATH=c:\nodist\bin;%PATH%
  - cmd: git clone https://github.com/marcelklehr/nodist.git c:\nodist 2>&1
  - cmd: SET NODIST_X64=0
  - cmd: call nodist update
  - cmd: call nodist stable
  - cmd: npm install node-gyp -g

build_script:
  - cmd: ECHO "BUILDING ia32 version:"
  - cmd: npm install --build-from-source --msvs_version=2013
  - cmd: SET PATH=%cd%\node_modules\.bin\;%PATH%
  - cmd: npm test
  - cmd: node-gyp clean
  - cmd: rmdir /q /s node_modules
  - cmd: ECHO "INSTALLING x64 node.js:"
  # We add newest MSBuild so we can use the correct libs for the x64 version
  - cmd: SET PATH=C:\Program Files (x86)\MSBuild\12.0\bin\;%PATH%
  - cmd: SET PATH=c:\python27;%PATH%
  - cmd: set NODIST_X64=1
  - cmd: call nodist stable
  - cmd: npm install node-gyp -g
  - cmd: ECHO "BUILDING x64 version:"
  - cmd: npm install --build-from-source --msvs_version=2013
  - cmd: npm test

on_success:
  # test installing from binary package works
  - cmd: ECHO "ON SUCCESS:"

test: OFF

deploy: OFF
