environment:
  matrix:
    - nodejs_version: 10
    - nodejs_version: 11
    - nodejs_version: 12
    - nodejs_version: 13
platform:
  - x64
  - x86

install:
  - npm install
  - npm test

build: OFF
test: OFF
deploy: OFF
