platforms:
  - x64
  - x32

environment:
  matrix:
    - nodejs_version: 0.8
    - nodejs_version: 0.10

install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version)
  - node --version
  - npm --version
  - npm install --build-from-source
  - npm test

build: OFF

test: OFF

test_script: OFF

deploy: OFF
