environment:
  matrix:
    - nodejs_version: 0.8
    - nodejs_version: 0.10
  node_pre_gyp_accessKeyId:
    secure: T1Pel/pv9SVfiVvZW8TLZnvZX6M4HQTiR7LUZnF1tuY=
  node_pre_gyp_secretAccessKey:
    secure: 8f5eTxMHpuVGHon2wbqrZuq3wzQfEuXMCcOyafBLza0T2VIOoBjbjDbgRbyRIzsT

platform:
  - x64
  - x86

install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version)
  - node --version
  - npm --version
  # ensure python is on path so that srs_settings.js are generated
  - SET PATH=c:\python27;%PATH%
  - npm install --build-from-source --msvs_version=2013
  - npm install mocha
  - npm test

build: OFF

test: OFF

test_script: OFF

deploy: OFF
