environment:
#  matrix:
#    - nodejs_version: 0.10
#    - nodejs_version: 0.8
  node_pre_gyp_accessKeyId:
    secure: T1Pel/pv9SVfiVvZW8TLZnvZX6M4HQTiR7LUZnF1tuY=
  node_pre_gyp_secretAccessKey:
    secure: 8f5eTxMHpuVGHon2wbqrZuq3wzQfEuXMCcOyafBLza0T2VIOoBjbjDbgRbyRIzsT

platform:
  - x64
#  - x86

install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version)
  - node --version
  - npm --version
  # ensure python is on path so that srs_settings.js are generated
  - SET PATH=c:\python27;%PATH%
  # ensure MSBuild 12 is found
  - SET PATH=C:\Program Files (x86)\MSBuild\12.0\bin\;%PATH%
  # add local node-pre-gyp dir to path
  - SET PATH=C:\projects\node-srs\node_modules\node-pre-gyp\bin;%PATH%
  # install node-gyp locally for node 0.8 build
  # otherwise node-gyp that comes with node is used and doesn't yet know about --msvs_version=2013
  - npm install node-gyp
  - npm install aws-sdk
  - npm install --build-from-source --msvs_version=2013
  - npm install mocha
  - npm test
  # make commit message env var shorter
  - SET CM=%APPVEYOR_REPO_COMMIT_MESSAGE%
  - ECHO commit message: %CM%
  - if not "%CM%" == "%CM:[publish binary]=%" node-pre-gyp --msvs_version=2013 package publish 2>&1

build: OFF

test: OFF

test_script: OFF

deploy: OFF
